In [47]:
l=(1,2,3,4,5,6)
n=np.array(l)
n

array([1, 2, 3, 4, 5, 6])

In [48]:
l1={1,2,3,4,5,6}
n1=np.array(l1)
n1

array({1, 2, 3, 4, 5, 6}, dtype=object)

In [49]:
l2=[1,2,3,4,5,6]
n2=np.array(l2)
n2

array([1, 2, 3, 4, 5, 6])

In [50]:
#to append values to array append() is used

#single element append
n3=np.append(n2,7)
n3

array([1, 2, 3, 4, 5, 6, 7])

In [51]:
#appending multiple elements

n4=np.append(n3,[8,9])
n4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
#to insert values to array at specified index insert() is used 

#inserting single element

n5=np.insert(n4,9,10)
n5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
#to insert multiple elements at required index

n6=np.insert(n5,10,[11,12,13])
n6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [55]:
#to delete values in array delete() is used

n7=np.delete(n6,np.where(n6==13))
n7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [56]:
#to delete multiple values in array using setdiff1d()

n8=np.setdiff1d(n7,[10,11,12])
n8

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
#to delete multiple values based on index

n9=np.delete(n8,[6,7,8])
n9

array([1, 2, 3, 4, 5, 6])

In [59]:
#check condition and print boolean values either TRUE or FALSE

n9<5

array([ True,  True,  True,  True, False, False])

In [61]:
#check conditions and print value if it is true

n9[n9<5]

array([1, 2, 3, 4])

In [62]:
#while checking multiple conditions and display boolean values

(n9<5) & (n9>0)

array([ True,  True,  True,  True, False, False])

In [63]:
#while checking multiple conditions and display values which satisfies condition

n9[(n9<5) & (n9>0)]

array([1, 2, 3, 4])

In [68]:
n9[n9==6]=10

In [69]:
n9

array([ 1,  2,  3,  4,  5, 10])

In [70]:
#to display zeros

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [71]:
#to display ones

np.ones(5)

array([1., 1., 1., 1., 1.])

In [72]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [74]:
np.zeros([2,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [75]:
np.ones([3,3],dtype='complex')

array([[1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j]])

In [77]:
np.zeros([3,3],dtype=float)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [78]:
np.zeros([3,3],dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [79]:
n9.tolist()

[1, 2, 3, 4, 5, 10]