In [15]:
np.arange(10) #for creating arange of elements

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
import numpy as np
n=[1,2,3,4,5,6,7,8,9,10,11]
a=np.array(n) #converting list into array
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
#it is used to reshape() the existing array
m=a.reshape(11,1)

In [12]:
m

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [27]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
a[1:4] #slicing

array([2, 3, 4])

In [29]:
a[-1:]

array([11])

In [21]:
#identity matrix can be created using two functions
#eye() ->used to define both user defined rows and columns
#identity() ->used to define same number of rows and columns 
md1=np.eye(5,6) #for identity  matrix 2 arguments or 1 arguments i.e 5rows,6columns

In [23]:
md1

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [19]:
md=np.identity(3) #identity matrix range can be only 1 argument i.e 3rows,3columns

In [20]:
md

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
m=np.arange(25).reshape(5,5)

In [31]:
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
#multidimensional array slicing
#ar2[row_start:row_end,column_start:column_end]
m[0:2,1:4]

array([[1, 2, 3],
       [6, 7, 8]])

In [33]:
m[1:3,1:3] #positive indexing

array([[ 6,  7],
       [11, 12]])

In [44]:
m[-4:-2,-4:-2] #using negative indexing 

array([[ 6,  7],
       [11, 12]])

In [47]:
np.mean(a)

6.0

In [48]:
np.arange(50).mean()

24.5

In [49]:
ar3=np.arange(50).reshape(5,10)

In [50]:
ar3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [59]:
ar3[-3:-1,-3:-2]

array([[27],
       [37]])

In [62]:
np.sum(ar3)

1225

In [60]:
np.sum(ar3,axis=0) #to add based on column wise axis=0

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145])

In [61]:
np.sum(ar3,axis=1) #to add based on column wise axis=1

array([ 45, 145, 245, 345, 445])

In [ ]:
#mean -->average
#median -->middle value
#mode -->repeated value
#variance -->median/total number of elements
#standard deviation -->square root of variance

In [64]:
np.mean(ar3)

24.5

In [63]:
np.median(ar3)

24.5

In [79]:
var=np.var(ar3) #variance
var

208.25

In [83]:
std=np.sqrt(var) #standard deviation
std

14.430869689661812

In [96]:
#linespace()
#It is used to print the evenly seperated point between two range values
np.linspace(0,100,5) #linspace(star,end,number of parts)

array([  0.,  25.,  50.,  75., 100.])

In [93]:
np.linspace(0,10,5,dtype=int) #dtype for converting datatype

array([ 0,  2,  5,  7, 10])

In [101]:
np.linspace(0,100,5,dtype=int,retstep=True)

(array([  0,  25,  50,  75, 100]), 25.0)

In [125]:
#random module
#np.random.randint(start,end)
np.random.randint(0,70)

20

In [108]:
#np.random.randint(range)
np.random.randint(100)

80

In [153]:
#np.random.randint(start,end,no_of_values)
np.random.randint(30,41,2)

array([31, 40])

In [159]:
#rand()
#To get the randomly generated values from 0 to 1,based on uniform distribution
np.random.rand(5)

0.47735304334467943

In [161]:
#normalised distribution
np.random.randn(5,4)

array([[-0.76417891,  1.31001105,  1.40701478, -0.02344011],
       [ 1.0151868 ,  0.68832914, -0.72710775,  0.13625374],
       [ 0.67526043,  0.33196923,  2.14953159, -0.188485  ],
       [ 0.70426608,  1.69517965, -0.29002529,  1.33744215],
       [ 0.80664907, -0.41753221,  0.92890037,  1.01943712]])

In [162]:
a.min() #min() -->for finding min value 

1

In [163]:
a.max() #max() -->for finding max value

11

In [169]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [181]:
a.argmax() #argmax() -->index of max value in array

9

In [183]:
a.argmin() #argmin() -->index of min value in array

0

In [188]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [187]:
np.cos((a))

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [189]:
np.tan(a)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [192]:
np.sin(a)/np.cos(a) #tan

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [193]:
np.cos(a)/np.sin(a)  #cot

C:\Users\HP\AppData\Local\Temp\ipykernel_14976\3202920359.py:1: RuntimeWarning: divide by zero encountered in divide
  np.cos(a)/np.sin(a)


array([        inf,  0.64209262, -0.45765755, -7.01525255,  0.86369115,
       -0.29581292, -3.436353  ,  1.14751542, -0.14706506, -2.21084541])

In [194]:
1/np.sin(a) #cosec

C:\Users\HP\AppData\Local\Temp\ipykernel_14976\1909192946.py:1: RuntimeWarning: divide by zero encountered in divide
  1/np.sin(a)


array([        inf,  1.18839511,  1.09975017,  7.0861674 , -1.32134871,
       -1.04283521, -3.57889955,  1.52210106,  1.01075622,  2.42648664])

In [195]:
1/np.cos(a) #sec

array([ 1.        ,  1.85081572, -2.40299796, -1.01010867, -1.52988566,
        3.52532009,  1.04148193,  1.3264319 , -6.87285064, -1.09753791])

In [215]:
np2=np.array([1,2,3])
np3=np.array([4,5,6])
#(1*4)+(2*5)+(3*6)
b=(np2[0]*np3[0])+(np2[1]*np3[1])+(np2[2]*np3[2])
b

32

In [262]:
np2=np.array([1,2,3,9])
np3=np.array([4,5,6,1])
#np2*np3
np.dot(np2,np3)

41

In [280]:
np2=np.array([1,2,3,8,1])
np3=np.array([4,5,6,8,9])
len1=len(np2)
len2=len(np3)
diff=len1-len2
diff1=abs(diff)
for i in range(diff):
    np3=np.append(np3,1)
np.dot(np2,np3)


        



105

In [245]:
np1=np.array([1,23,4,5,6,7,np.nan,np.nan,np.nan])
np1

array([ 1., 23.,  4.,  5.,  6.,  7., nan, nan, nan])

In [246]:
print(np1[np.isnan(np1)])

[nan nan nan]


In [248]:
print(np1[~np.isnan(np1)])

[ 1. 23.  4.  5.  6.  7.]


In [255]:
pip list


Package                       Version
----------------------------- ---------------
alabaster                     0.7.12
anaconda-client               1.11.2
anaconda-navigator            2.4.0
anaconda-project              0.11.1
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
astroid                       2.14.2
astropy                       5.1
asttokens                     2.0.5
atomicwrites                  1.4.0
attrs                         22.1.0
Automat                       20.2.0
autopep8                      1.6.0
Babel                         2.11.0
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
backports.tempfile            1.0
backports.weakref             1.0.post1
bcrypt                        3.2.0
beautifulsoup4                4.11.1
binaryornot                   0.4.4
black                         22.6.0
bleac

In [256]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [268]:
#Pandas
import pandas as pd
#Pandas is defined as an open_source library that provides high-performance data manipulation in python.

#Data analysis required lot of processing such as restructuring,cleaning,merging,manipilating etc... 

#We prefer Pandas to perform above functionalities coz it is fast,simple than other tools.

#Pandas is built on Numpy,Numpy is required for operating pandas


In [281]:
#Pandas series 

#Pandas series is a data structure with one dimensional labeled array

#It is a primary building block of Dataframe,making its rows and columns

#Syntax -->pandas.series(data=None,index=None,dtype=None,name=None,copy=True or False)

In [285]:
labels=['a','b','c']
my_data=[10,20,30]
arr=np.array(my_data)
d={'a':100,'b':200,'c':300}


In [292]:
#ex:1

import pandas as pd
pd.Series(my_data)

0    10
1    20
2    30
dtype: int64

In [293]:
type(pd.Series(my_data))

pandas.core.series.Series

In [300]:
#Series with labels

#pd.Series(my_data,labels)

       #or

pd.Series(data=my_data,index=labels)

a    10
b    20
c    30
dtype: int64

In [304]:
pd.Series(data=[print(),len,sum])

0                       None
1    <built-in function len>
2                         41
dtype: object

In [320]:
class profile:
    #@property
    def display(self):
        print("my name is vinay")
p=profile()
p.display()
      

def greet():
    return "Good afternoon"
    
def decor(func):
    def inner():
        str1=func()
        return str1.lower()
    return inner()

print(decor(greet))

my name is vinay
good afternoon


In [321]:
series=pd.Series([1,2,3,4,5],['USA','INDIA','CANADA','UK','EGYPT',])

In [323]:
series

USA       1
INDIA     2
CANADA    3
UK        4
EGYPT     5
dtype: int64

In [324]:
series['USA'] #value using key

1

In [327]:
series[0] #value using indexing

1

In [328]:
series[1:]

INDIA     2
CANADA    3
UK        4
EGYPT     5
dtype: int64

In [329]:
series[-1:]

EGYPT    5
dtype: int64

In [331]:
series[::-1]

EGYPT     5
UK        4
CANADA    3
INDIA     2
USA       1
dtype: int64

In [339]:
ser=pd.Series([1,2,3,4,5],['A','B','C','D','E'])


In [340]:
series+ser

A        NaN
B        NaN
C        NaN
CANADA   NaN
D        NaN
E        NaN
EGYPT    NaN
INDIA    NaN
UK       NaN
USA      NaN
dtype: float64

In [341]:
ser[::-1]

E    5
D    4
C    3
B    2
A    1
dtype: int64

In [342]:
#To create a new data in series

ser

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [350]:
series['CHINA']="SIX"

In [351]:
series

USA         1
INDIA       2
CANADA      3
UK          4
EGYPT       5
CHINA     SIX
dtype: object

In [353]:
series.drop('CHINA')

USA       1
INDIA     2
CANADA    3
UK        4
EGYPT     5
dtype: object

In [356]:
#Dataframe 
#p.DataF

#pd.DataFrame(datas,row_label,col_label)

df=pd.DataFrame(np.random.randn(5,4))

In [357]:
df

0         1         2         3
0  0.000717  0.715169 -1.394831  0.281103
1 -0.157472  1.995142 -0.888137  0.336537
2  1.129633 -0.001685 -0.685405  0.995337
3 -0.404034 -0.848299 -1.345435 -1.627834
4 -0.105560  0.658154  0.343551  0.293631

In [390]:
df=pd.DataFrame(np.random.randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [385]:
df

W         X         Y         Z
A  1.069897 -0.143353 -0.671405  0.977698
B  1.244194 -0.691350 -0.840285  0.199231
C -0.915070 -0.302651  0.970236 -1.424221
D -0.652358 -1.496002  0.837181  0.195437
E -0.690583 -0.378840  0.832258  0.189524

In [362]:
# To convert dictionary into DataFrame

d={"col1":[1,2],"col2":[3,4],"col3":[5,6]}

In [386]:
df=pd.DataFrame(data=d,index=['row1','row2'])

                     #or
    
#df=pd.DataFrame(d,['row1','row2'])

In [387]:
d1

col1  col2  col3
row1     1     3     5
row2     2     4     6

In [391]:
df.T  #Transpose matrix

A         B         C         D         E
W -0.957667  1.457134  0.960571  0.084726 -0.764508
X -0.448264 -0.360486  0.224989  1.100182 -0.293663
Y -0.051915  0.774760 -1.019336  1.564261 -0.707130
Z -1.242098  1.274351 -0.742965  0.046712  1.147353

In [393]:
df.index    #Row names

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [395]:
df.columns  #Column names

Index(['W', 'X', 'Y', 'Z'], dtype='object')

In [396]:
type(df)

pandas.core.frame.DataFrame

In [398]:
df.dtypes

W    float64
X    float64
Y    float64
Z    float64
dtype: object

In [400]:
df.info()   #to get information about dataframes

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, A to E
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   W       5 non-null      float64
 1   X       5 non-null      float64
 2   Y       5 non-null      float64
 3   Z       5 non-null      float64
dtypes: float64(4)
memory usage: 372.0+ bytes


In [401]:
df.values

array([[-0.95766737, -0.44826422, -0.05191548, -1.24209832],
       [ 1.45713423, -0.36048626,  0.77475985,  1.27435072],
       [ 0.96057093,  0.22498851, -1.01933555, -0.74296526],
       [ 0.08472614,  1.10018237,  1.56426127,  0.04671246],
       [-0.76450836, -0.29366324, -0.70713049,  1.1473534 ]])

In [402]:
df.axes

[Index(['A', 'B', 'C', 'D', 'E'], dtype='object'),
 Index(['W', 'X', 'Y', 'Z'], dtype='object')]

In [403]:
df.ndim

2

In [404]:
df.size

20

In [405]:
 df

W         X         Y         Z
A -0.957667 -0.448264 -0.051915 -1.242098
B  1.457134 -0.360486  0.774760  1.274351
C  0.960571  0.224989 -1.019336 -0.742965
D  0.084726  1.100182  1.564261  0.046712
E -0.764508 -0.293663 -0.707130  1.147353

In [408]:
#To access specific column in dataframes

df['W']

A   -0.957667
B    1.457134
C    0.960571
D    0.084726
E   -0.764508
Name: W, dtype: float64

In [409]:
#type(df['W'])

pandas.core.series.Series

In [412]:
#To access multiple columns 

df[['W','X','Y']]

W         X         Y
A -0.957667 -0.448264 -0.051915
B  1.457134 -0.360486  0.774760
C  0.960571  0.224989 -1.019336
D  0.084726  1.100182  1.564261
E -0.764508 -0.293663 -0.707130

In [415]:
#To create new column 

df['new']=df['W']+df['Y']

In [429]:
df

W         X         Y         Z
A -0.957667 -0.448264 -0.051915 -1.242098
B  1.457134 -0.360486  0.774760  1.274351
C  0.960571  0.224989 -1.019336 -0.742965
D  0.084726  1.100182  1.564261  0.046712
E -0.764508 -0.293663 -0.707130  1.147353

In [432]:
df['new']=df['W']+df['Y']

In [433]:
df.drop("new",axis=1,inplace=True)

In [434]:
df

W         X         Y         Z
A -0.957667 -0.448264 -0.051915 -1.242098
B  1.457134 -0.360486  0.774760  1.274351
C  0.960571  0.224989 -1.019336 -0.742965
D  0.084726  1.100182  1.564261  0.046712
E -0.764508 -0.293663 -0.707130  1.147353